[package]
name = "test0"
version = "0.1.0"
authors = ["Bert Belder <bertbelder@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.13"
libc = "0.2.91"
tokio = { version = "1.4.0", features = ["full"] }
